# Generated by Django 3.0.7 on 2020-10-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='supplement',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
